name: Cache Workflow (d5b8836)


on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-d5b8836

      - name: prime-cache-d5b8836
        run: echo "Cache result was ${{ steps.cache.outputs.cache-hit }}"
